import React from "react";

const IconRefCalculate = () => {
  return (
    <svg
      id="Layer_2"
      data-name="Layer 2"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 66.4 66.4"
    >
      <g id="MainScroll">
        <g id="_6_Icons02" data-name="6_Icons02">
          <g>
            <g>
              <line
                className="cls-1"
                fill="none"
                stroke="#1f2820"
                strokeLinecap="round"
                strokeMiterlimit="10"
                strokeWidth="1.4px"
                x1="33.2"
                y1=".7"
                x2="33.2"
                y2="65.7"
              />
              <line
                className="cls-1"
                fill="none"
                stroke="#1f2820"
                strokeLinecap="round"
                strokeMiterlimit="10"
                strokeWidth="1.4px"
                x1=".7"
                y1="33.2"
                x2="65.7"
                y2="33.2"
              />
              <g>
                <line
                  className="cls-1"
                  fill="none"
                  stroke="#1f2820"
                  strokeLinecap="round"
                  strokeMiterlimit="10"
                  strokeWidth="1.4px"
                  x1="16.64"
                  y1="9.59"
                  x2="16.64"
                  y2="22.34"
                />
                <line
                  className="cls-1"
                  fill="none"
                  stroke="#1f2820"
                  strokeLinecap="round"
                  strokeMiterlimit="10"
                  strokeWidth="1.4px"
                  x1="10.27"
                  y1="15.97"
                  x2="23.02"
                  y2="15.97"
                />
              </g>
              <g>
                <line
                  className="cls-1"
                  fill="none"
                  stroke="#1f2820"
                  strokeLinecap="round"
                  strokeMiterlimit="10"
                  strokeWidth="1.4px"
                  x1="12.14"
                  y1="45.92"
                  x2="21.15"
                  y2="54.94"
                />
                <line
                  className="cls-1"
                  fill="none"
                  stroke="#1f2820"
                  strokeLinecap="round"
                  strokeMiterlimit="10"
                  strokeWidth="1.4px"
                  x1="12.14"
                  y1="54.94"
                  x2="21.15"
                  y2="45.92"
                />
              </g>
              <line
                className="cls-1"
                fill="none"
                stroke="#1f2820"
                strokeLinecap="round"
                strokeMiterlimit="10"
                strokeWidth="1.4px"
                x1="43.58"
                y1="50.43"
                x2="56.33"
                y2="50.43"
              />
              <line
                className="cls-1"
                fill="none"
                stroke="#1f2820"
                strokeLinecap="round"
                strokeMiterlimit="10"
                strokeWidth="1.4px"
                x1="43.58"
                y1="15.97"
                x2="56.33"
                y2="15.97"
              />
            </g>
            <circle
              className="cls-1"
              fill="none"
              stroke="#1f2820"
              strokeLinecap="round"
              strokeMiterlimit="10"
              strokeWidth="1.4px"
              cx="49.96"
              cy="46.79"
              r=".16"
            />
            <circle
              className="cls-1"
              fill="none"
              stroke="#1f2820"
              strokeLinecap="round"
              strokeMiterlimit="10"
              strokeWidth="1.4px"
              cx="49.96"
              cy="54.08"
              r=".16"
            />
          </g>
        </g>
      </g>
    </svg>
  );
};

export default IconRefCalculate;
