import React from "react";

const IconTime = () => {
  return (
    <svg
      id="Layer_2"
      data-name="Layer 2"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 115.57 115.57"
      className="w-full h-full"
    >
      <g id="MainScroll">
        <g id="_2_Icons" data-name="2_Icons">
          <g>
            <g>
              <circle
                className="cls-1"
                fill="none"
                stroke="#2c2f30"
                strokeMiterlimit="10"
                strokeWidth="1.4px"
                cx="57.79"
                cy="62.3"
                r="32.89"
              />
              <circle
                className="cls-1"
                fill="none"
                stroke="#2c2f30"
                strokeMiterlimit="10"
                strokeWidth="1.4px"
                cx="57.79"
                cy="62.3"
                r="22.54"
              />
              <line
                className="cls-1"
                fill="none"
                stroke="#2c2f30"
                strokeMiterlimit="10"
                strokeWidth="1.4px"
                x1="57.79"
                y1="29.41"
                x2="57.79"
                y2="21.63"
              />
              <line
                className="cls-1"
                fill="none"
                stroke="#2c2f30"
                strokeMiterlimit="10"
                strokeWidth="1.4px"
                x1="47.11"
                y1="20.37"
                x2="68.46"
                y2="20.37"
              />
              <polyline
                className="cls-1"
                fill="none"
                stroke="#2c2f30"
                strokeMiterlimit="10"
                strokeWidth="1.4px"
                points="49.71 62.01 56.06 68.73 66.86 52.06"
              />
              <g>
                <line
                  className="cls-1"
                  fill="none"
                  stroke="#2c2f30"
                  strokeMiterlimit="10"
                  strokeWidth="1.4px"
                  x1="77.54"
                  y1="35.38"
                  x2="81.59"
                  y2="30.04"
                />
                <line
                  className="cls-1"
                  fill="none"
                  stroke="#2c2f30"
                  strokeMiterlimit="10"
                  strokeWidth="1.4px"
                  x1="77.71"
                  y1="25.74"
                  x2="86.78"
                  y2="32.62"
                />
              </g>
              <g>
                <line
                  className="cls-1"
                  fill="none"
                  stroke="#2c2f30"
                  strokeMiterlimit="10"
                  strokeWidth="1.4px"
                  x1="37.34"
                  y1="35.38"
                  x2="33.28"
                  y2="30.04"
                />
                <line
                  className="cls-1"
                  fill="none"
                  stroke="#2c2f30"
                  strokeMiterlimit="10"
                  strokeWidth="1.4px"
                  x1="37.16"
                  y1="25.74"
                  x2="28.1"
                  y2="32.62"
                />
              </g>
            </g>
            <circle
              className="cls-1"
              fill="none"
              stroke="#2c2f30"
              strokeMiterlimit="10"
              strokeWidth="1.4px"
              cx="57.79"
              cy="57.79"
              r="57.09"
            />
          </g>
        </g>
      </g>
    </svg>
  );
};

export default IconTime;
